### PR TITLE
implement #4688 and implement #5236

### PR DESCRIPTION
**Pull request by ToMe25**
Disable Free Runners while Sneaking and add Sawing Factories.

### CODE REVIEW

**Comment by thiakil** [comment]
Looks good on the surface, thanks!

Could I possibly trouble you to split it into 2 PRs? The freerunners one is easy and I can do right away, but the factories is a little trickier, especially as things are in a state of flux behind the scenes.

**Comment by ToMe25** [comment]
can i just make a small additional one for the Free Runners and let them in here or would that cause problems?

**Comment by thiakil** [comment]
If you're not sure how to do it, that's fine, I'll get to it later, that's all :)

**Comment by ToMe25** [comment]
Than i think i wont split it :)

**Comment by aidancbrady** [comment]
Due to the code reformat these changes will probably need to be manually merged in. I'd be happy to tackle this once we get more things done, but if you have any free time @ToMe25 you could certainly speed up the process by pulling the latest changes and making sure everything lines up.

Sorry for the messiness :)

**Comment by ToMe25** [comment]
1. seems like github doesn't checks conflicts in the Way i was thinking.
2. even without my changes but with the new Sources my IDE tells me there are 30 errors.
3. even without my changes but with the new Sources it Crashes with this Crash Report: 
[crash-2019-03-28_11.08.00-client.txt](https://github.com/mekanism-mod/Mekanism/files/3017370/crash-2019-03-28_11.08.00-client.txt)

**Comment by ToMe25** [comment]
I think i finished it :)

**Comment by ToMe25** [comment]
@thiakil Your last comment is now a week ago, anything new about this?

**Comment by thiakil** [comment]
Unfortunately not, the big merge is yet to happen :(

**Comment by dizzyd** [comment]
Hi @ToMe25 - I've just merged Mekanica into Mekanism on the 1.12 branch. Unfortunately, that has generated some conflicts that will need to be resolved before we can merge this PR. Thanks!

**Comment by ToMe25** [comment]
@dizzyd why did you closed this without any comment?

**Comment by ToMe25** [comment]
@dizzyd As i can't resolve/merge that on the website, can't pull it back to my repo, don't know enough about git for doing it using the commandline like github suggests and the github commandline pull request/resolve example/tutorial isn't working for me i can't resolve that.

**Comment by pupnewfster** [comment]
> @dizzyd As i can't resolve/merge that on the website, can't pull it back to my repo, don't know enough about git for doing it using the commandline like github suggests and the github commandline pull request/resolve example/tutorial isn't working for me i can't resolve that.

There are a couple options, one just fork it again and compare against your branch to see what you changed to do it again, or give us a bit and we will look at it at some point when we are working on merging things in.

**Comment by pupnewfster** [comment]
Closing this for now as I ported the first part in https://github.com/mekanism-mod/Mekanism/commit/8a0382877ac7b234b74db6128d20900e069b2d9e and the remainder is now sitting in #5383 Thanks again for your contribution.

**Pull request closed without merging**
